openapi: 3.0.0
info:
  title: ClearFlask API
  description: ClearFlask API documentation.
  version: 1.0.0

servers:
  - url: https://api.clearflask.com/v1

externalDocs:
  url: https://clearflask.com/docs

paths:
  # api-client.yaml
  /project/{projectId}/idea:
    $ref: 'api-idea.yaml#/~1project~1{projectId}~1idea'
  /project/{projectId}/idea/{ideaId}:
    $ref: 'api-idea.yaml#/~1project~1{projectId}~1idea~1{ideaId}'
  /project/{projectId}/login:
    $ref: 'api-user.yaml#/~1project~1{projectId}~1login'
  /project/{projectId}/user:
    $ref: 'api-user.yaml#/~1project~1{projectId}~1user'
  /project/{projectId}/user/{userId}:
    $ref: 'api-user.yaml#/~1project~1{projectId}~1user~1{userId}'
  /project/{projectId}/idea/{ideaId}/comment:
    $ref: 'api-comment.yaml#/~1project~1{projectId}~1idea~1{ideaId}~1comment'
  /project/{projectId}/idea/{ideaId}/comment/{commentId}:
    $ref: 'api-comment.yaml#/~1project~1{projectId}~1idea~1{ideaId}~1comment~1{commentId}'
  /project/{projectId}/user/{userId}/credit:
    $ref: 'api-credit.yaml#/~1project~1{projectId}~1user~1{userId}~1credit'
  /project/{projectId}/idea/{ideaId}/vote:
    $ref: 'api-vote.yaml#/~1project~1{projectId}~1idea~1{ideaId}~1vote'
  /project/{projectId}/idea/{ideaId}/vote/{voteId}:
    $ref: 'api-vote.yaml#/~1project~1{projectId}~1idea~1{ideaId}~1vote~1{voteId}'
  /project/{projectId}/config:
    $ref: 'api-project.yaml#/~1project~1{projectId}~1config'
  # api-admin.yaml
  /project/{projectId}/admin/idea:
    $ref: 'api-idea.yaml#/~1project~1{projectId}~1admin~1idea'
  /project/{projectId}/admin/idea/{ideaId}:
    $ref: 'api-idea.yaml#/~1project~1{projectId}~1admin~1idea~1{ideaId}'
  /admin/login:
    $ref: 'api-user.yaml#/~1admin~1login'
  /project/{projectId}/admin/user:
    $ref: 'api-user.yaml#/~1project~1{projectId}~1admin~1user'
  /project/{projectId}/admin/user/{userId}:
    $ref: 'api-user.yaml#/~1project~1{projectId}~1admin~1user~1{userId}'
  /project/{projectId}/admin/comment:
    $ref: 'api-comment.yaml#/~1project~1{projectId}~1admin~1comment'
  /project/{projectId}/admin/idea/{ideaId}/comment:
    $ref: 'api-comment.yaml#/~1project~1{projectId}~1admin~1idea~1{ideaId}~1comment'
  /project/{projectId}/admin/idea/{ideaId}/comment/{commentId}:
    $ref: 'api-comment.yaml#/~1project~1{projectId}~1admin~1idea~1{ideaId}~1comment~1{commentId}'
  /project/{projectId}/admin/user/{userId}/credit:
    $ref: 'api-credit.yaml#/~1project~1{projectId}~1admin~1user~1{userId}~1credit'
  /project/{projectId}/admin/credit:
    $ref: 'api-credit.yaml#/~1project~1{projectId}~1admin~1credit'
  /project/{projectId}/admin/vote:
    $ref: 'api-vote.yaml#/~1project~1{projectId}~1admin~1vote'
  /project/{projectId}/admin/idea/{ideaId}/vote:
    $ref: 'api-vote.yaml#/~1project~1{projectId}~1admin~1idea~1{ideaId}~1vote'
  /project/{projectId}/admin/idea/{ideaId}/vote/{voteId}:
    $ref: 'api-vote.yaml#/~1project~1{projectId}~1admin~1idea~1{ideaId}~1vote~1{voteId}'
  /project/admin:
    $ref: 'api-project.yaml#/~1project~1admin'
  /project/{projectId}/admin/config:
    $ref: 'api-project.yaml#/~1project~1{projectId}~1admin~1config'
