image: maven:3.6.3-openjdk-11

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

services:
  - docker:dind

before_script:
  - apt-get update -qq && apt-get install -qqy protobuf-compiler docker-compose pass
  - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  - useradd -d /builds/${GITLAB_USER_LOGIN} --non-unique --system --uid 1000 -g users -M -N runner

stages:
  - build

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - sudo -H -u runner -i sh -e -x << EOS
    mvn $MAVEN_CLI_OPTS install
    EOS
