image: ayan4m1/maven-node:latest

before_script:
  - npm install swagger-parser @openapitools/openapi-generator-cli@cli-4.1.3 -g
  - openapi-generator version

stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS install
