version: '3.8'
volumes:
  db:
services:
  clearflask-connect:
    ports:
      - 80:3000
    image: 'clearflask/clearflask-connect:latest'
    depends_on:
      - clearflask-server
  clearflask-server:
    ports:
      - 8080:8080
    image: 'clearflask/clearflask-server:latest'
