version: '3.8'
services:
  clearflask-connect:
    image: ghcr.io/clearflask/clearflask-connect:latest
    depends_on:
      - clearflask-server
    ports:
      - 80:3000
    environment:
      - NODE_ENV=production
      - ENV=selfhost
    volumes:
      - ./connect.config.json:/opt/clearflask/connect.config.json
  clearflask-server:
    image: ghcr.io/clearflask/clearflask-server:latest
    ports:
      - 8080:8080
    environment:
      - CLEARFLASK_ENVIRONMENT=PRODUCTION_SELF_HOST
    volumes:
      - ./config-selfhost.cfg:/opt/clearflask/config-prod.cfg
