version: '3.8'
volumes:
  data:
    driver: local
services:
  # ElasticSearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    expose:
      - 9200
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
    mem_limit: 4g
    volumes:
      - data/elasticsearch:/usr/share/elasticsearch/data
  # (Optional) ElasticSearch web ui
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  # For DynamoDB alternative
  minio:
    image: minio/minio
    ports:
      - 9001:9001
    expose:
      - 9000
    volumes:
      - data/minio:/data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  # For DynamoDB
  localstack:
    image: localstack/localstack
    expose:
      - 4566
      - 4571
    environment:
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=dynamodb
      - LS_LOG=warn
      - START_WEB=0
      - USE_SSL=0
      - FORCE_NONINTERACTIVE=true
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - data/localstack:/tmp/localstack
