## SPDX-FileCopyrightText: 2019-2022 Matus Faro <matus@smotana.com>
## SPDX-License-Identifier: Apache-2.0
openapi: 3.0.0
info:
  title: ClearFlask Connect API
  description: ClearFlask API documentation.
  version: 1.0.0

servers:
  - url: https://clearflask.com/api/v1

paths:
  /connect/cert/challenge/http:
    $ref: 'api-sni.yaml#/~1connect~1cert~1challenge~1http'
  /connect/cert:
    $ref: 'api-sni.yaml#/~1connect~1cert'
  /connect/robots/slug/{slug}:
    $ref: 'api-robots.yaml#/~1connect~1robots~1slug~1{slug}'
