version: '3.2'
volumes:
  db:
services:
  clearflask-killbill-engine:
    image: killbill/killbill:0.22.10
    ports:
      - "8082:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://clearflask-killbill-db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
  clearflask-killbill-kaui:
    image: killbill/kaui:2.0.5
    ports:
      - "8081:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://clearflask-killbill-db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://clearflask-killbill-engine:8080
  clearflask-killbill-db:
    image: killbill/mariadb:0.22
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
